FROM apache/airflow:2.7.3-python3.10

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ && \
    rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-databricks==5.0.0 \
    apache-airflow-providers-microsoft-azure==8.5.0 \
    great-expectations==0.18.8
